server:
  port: 9002

eureka:
  client:
    service-url:
#      defaultZone: http://eureka-sv:8761/eureka
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 0
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: brand-sv
    datasource:
      driver-class-name: org.postgresql.Driver
      password: ${POSTGRES_PASSWORD}
      url: ${POSTGRES_URL}
      username: ${POSTGRES_USER}
    jpa:
      database: POSTGRESQL
      generate-ddl: true
      hibernate:
        ddl-auto: update
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    sql:
      init:
        platform: postgres
  servlet:
    multipart:
      max-file-size: 10MB