version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      - DATABASE_HOST=127.0.0.1  
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - 'stocksuite-network'
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - 'stocksuite-network'
  eureka-sv:
    build: eureka-sv
    mem_limit: 512m
    ports:
      - "8761:8761"
    networks:
      - 'stocksuite-network'    
  api-gateway:
    build: api-gateway
    mem_limit: 512m
    ports:
      - "443:443"
    networks:
      - 'stocksuite-network'
  config-server:
    build: config-server
    mem_limit: 512m
    ports:
      - "8081:8081"
    networks:
      - 'stocksuite-network'
  image-sv:
    build: image-sv
    environment:
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
    mem_limit: 512m
    ports:
      - "9005:9005"
    networks:
      - 'stocksuite-network'
  supplierpricelist-sv:
    build: supplierPriceList-sv
    environment:
      - POSTGRES_URL=${POSTGRES_DOCKER_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    mem_limit: 512m
    ports:
      - "9007:9007"
    networks:
      - 'stocksuite-network'
#  product-sv:
#    build: product-sv
#    mem_limit: 512m
#    ports:
#      - "9001:9001"
#    networks:
#      - 'stocksuite-network'
#  brand-sv:
#    build: brand-sv
#    mem_limit: 512m
#    ports:
#      - "9002:9002"
#    networks:
#      - 'stocksuite-network'
#  category-sv:
#    build: category-sv
#    mem_limit: 512m
#    ports:
#      - "9003:9003"
#    networks:
#      - 'stocksuite-network'
networks:
  stocksuite-network: