version: '1.1'

services:
  eureka-sv:
    build: eureka-sv
    mem_limit: 512m
    ports:
      - "8761:8761"
    networks:
      - 'stocksuite-network'    
  api-gateway:
    build: api-gateway
    mem_limit: 512m
    ports:
      - "443:443"
    networks:
      - 'stocksuite-network'
  config-server:
    build: config-server
    mem_limit: 512m
    ports:
      - "8081:8081"
    networks:
      - 'stocksuite-network'
#  image-sv:
#    build: image-sv
#   mem_limit: 512m
#    ports:
#      - "9005:9005"
#    networks:
#      - 'stocksuite-network'
#  product-sv:
#    build: product-sv
#    mem_limit: 512m
#    ports:
#      - "9001:9001"
#    networks:
#      - 'stocksuite-network'
#  brand-sv:
#    build: brand-sv
#    mem_limit: 512m
#    ports:
#      - "9002:9002"
#    networks:
#      - 'stocksuite-network'
#  category-sv:
#    build: category-sv
#    mem_limit: 512m
#    ports:
#      - "9003:9003"
#    networks:
#      - 'stocksuite-network'
networks:
  stocksuite-network:
