eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 0
server:
  port: 443
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true