eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9004
spring:
  application:
    name: brand-sv
    datasource:
      password: ${POSTGRES_PASSWORD}
      url: jdbc:postgresql://localhost:5432/db_easyStock_brand
      username: ${POSTGRES_USER}
    jpa:
      database: POSTGRESQL
      generate-ddl: true
      hibernate:
        ddl-auto: update
      show-sql: true
    sql:
      init:
        platform: postgres