eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 0
server:
  port: 9003
spring:
  application:
    name: category-sv
  datasource:
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/db_easyStock_category
    username: ${POSTGRES_USER}
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgres