spring:
  application:
    name: image-sv
  main:
    allow-bean-definition-overriding: true
server:
  port: 9005
eureka:
  client:
    service-url:
#      defaultZone: http://eureka-sv:8761/eureka
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 0


