eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 0
server:
  port: 9007
spring:
  application:
    name: supplierPriceList-sv
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 5
    password: ${SUPABASE_PASSWORD}
    url: ${SUPABASE_URL}
    username: ${SUPABASE_USER}
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
  sql:
    init:
      platform: postgres