spring:
  application:
    name: eureka-sv
server.port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  #Solucion al error CLAIMING INSTANCES
  instance:
    lease-renewal-interval-in-seconds: 0