server:
  port: 9002

spring:
  application:
    name: brand-sv
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    datasource:
      url: ${POSTGRES_URL}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        connection-timeout: 60000
        minimum-idle: 5
        maximum-pool-size: 20
        idle-timeout: 300000
        max-lifetime: 1800000
  servlet:
    multipart:
      max-file-size: 10MB

# EUREKA SERVER
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 0

# Configuración del acceso a Actuator (descomentar si se requiere)
# management:
#   endpoints:
#     web:
#       exposure:
#         include: '*'
#       base-path: /actuator
#   endpoint:
#     health:
#       show-details: always

# Otras configuraciones comentadas
# spring.config.import: optional:configserver:http://localhost:8081
# eureka.instance.instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}