eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 0

server:
  port: 8081

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/crishof/easyStockSuite.git
          search-paths: /backend/config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
